apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "gpu-hog.fullname" . }}
  labels:
{{ include "gpu-hog.labels" . | indent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "gpu-hog.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "gpu-hog.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      nodeSelector:
        nodeType: gpu
      containers:
      - image: {{ .Vaules.image.repository }}:{{ .Vaules.image.tag }}
        name: tf
        command:
        - "python"
        - "-c"
        - |
          import tensorflow as tf
          ngpu = 1
          sess = tf.Session(config=tf.ConfigProto(log_device_placement=True))
          while True:
              c = []
              for i in range(ngpu):
                  d = "/device:GPU:" + str(i)
                  with tf.device(d):
                      a = tf.random.uniform([2000, 3000], minval=0.0, maxval=1.0)
                      b = tf.random.uniform([3000, 2000], minval=0.0, maxval=1.0)
                      c.append(tf.linalg.matmul(a, b))
              with tf.device('/cpu:0'):
                  sum = tf.add_n(c)
              print(sess.run(sum))
