{{- if .Values.prometheus.monitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "prometheus-node-exporter-gpu.fullname" . }}
  labels: {{ include "prometheus-node-exporter-gpu.labels" . | indent 4 }}
  {{- if .Values.prometheus.monitor.additionalLabels }}
{{ toYaml .Values.prometheus.monitor.additionalLabels | indent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      app: {{ template "prometheus-node-exporter-gpu.name" . }}
      release: {{ .Release.Name }}
  endpoints:
    - port: metrics
{{- end }}
